name: CI/CD FOR PRODUCTION

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploying to Digital Ocean
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      DATABASE_URL: ${{secrets.PROD_DB}}
      AT_SECRET_KEY: ${{secrets.PROD_AT_JWT_SECRET}}
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      RT_SECRET_KEY: ${{secrets.PROD_RT_SECRET_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build for development
        run: yarn build

      - name: deploying to Digital Ocean..
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/backend
          remote_host: ${{ secrets.PROD_SERVER }}
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY }}

      - name: run migration
        run: yarn prisma migrate deploy
